### ISSUE TITLE
Missing dirs/files

### ISSUE THREAD

**Issue by jjcale** [Foggs/phaser-hangman#1]
Hi, 
I cannot find the following files, am I missing something?

 <script src="dist/bundle.js"></script>
 <script src="node_modules/phaser-input/build/phaser-input.js"></script>

Thanks!
JJ

**Comment by Foggs** [comment]
Enter 'npm install' in the terminal to install the dependencies then enter 'npm run dev' webpack will compile and you should see the project on as http://localhost:3000, I updated the README with the instructions

**Comment by jjcale** [comment]
yes, worked. Thanks!
